---
global:
  pattern: rhoso-gitops
  secretStore:
    backend: "none"
  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic
main:
  clusterGroupName: standalone
  multiSourceConfig:
    enabled: true
