---
global:
  pattern: rhoso-gitops
  secretLoader:
    disabled: false
  secretStore:
    backend: none
  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic
main:
  clusterGroupName: standalone
  multiSourceConfig:
    enabled: true
    clusterGroupChartVersion: "0.9.*"
