---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - nmstate-operator
  - metallb-operator
  - cluster-observability-operator
  - namespace-openstack.yaml
components:
  - ../../../initialize/gitops/components/annotations
